language: php
sudo: false

env:
  - XDEBUG_MODE=coverage

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 8.0

before_install:
  - composer self-update

cache:
  directories:
    - $HOME/.composer/cache

install: composer update --prefer-dist --no-interaction

script:
  - composer test
  - composer analyze

after_success:
  - travis_retry php vendor/bin/coveralls
